#!/bin/sh
# [Gedit Tool]
# Name=fpcBuild
# Shortcut=F5
# Languages=pascal
# Applicability=all
# Output=output-panel
# Input=nothing
# Save-files=document


# fpcBuild (FreePascal Build) gedit Plugin Copyright (c) 2011 Florian Harbecke

DOC_DIR=$(echo $GEDIT_CURRENT_DOCUMENT_DIR | sed "s#$HOME#~#")

# OUTPUT=$(fpc $GEDIT_CURRENT_DOCUMENT_NAME 2> /dev/null | awk '{if ($1 > 0 && /compiled/ && /sec/) {print "ok"} else {print "fail"}}')
OUTPUT=$(fpc $GEDIT_CURRENT_DOCUMENT_NAME 2> /dev/null | awk '{print $0" |"}')

for 

echo $OUTPUT

if echo $OUTPUT | grep compiled > /dev/null
then
	echo $OUTPUT | grep "[0-9]+ lines compiled, [0-9]+\.[0-9] sec"
else
	echo $OUPUT | awk '{print $1" "$3"fehler: "$5" erwartet, aber "$8" gefunden"}'
fi
# echo "Compiling $GEDIT_CURRENT_DOCUMENT_NAME ($DOC_DIR)"
# Using & so gedit won't freeze if fpc crashes
# fpc $GEDIT_CURRENT_DOCUMENT_PATH &
