#!/bin/sh
# [Gedit Tool]
# Name=fpcBuild
# Shortcut=F5
# Languages=pascal
# Applicability=all
# Output=output-panel
# Input=nothing
# Save-files=document


# fpcBuild (FreePascal Build) gedit Plugin Copyright (c) 2011 Florian Harbecke

DOC_DIR=`echo ${GEDIT_CURRENT_DOCUMENT_DIR} | sed "s#$HOME#~#"`

if fpc $GEDIT_CURRENT_DOCUMENT_NAME | awk '$1 > 0 && /compiled/ && /sec/{print "ok"}' | grep ok > /dev/null
then
	echo "Okay"
fi
# echo "Compiling $GEDIT_CURRENT_DOCUMENT_NAME ($DOC_DIR)"
# Using & so gedit won't freeze if fpc crashes
# fpc $GEDIT_CURRENT_DOCUMENT_PATH &
