#!/bin/sh
# [Gedit Tool]
# Name=FPCompile
# Shortcut=F5
# Languages=pascal
# Applicability=all
# Output=output-panel
# Input=nothing
# Save-files=document


# FPCompile (FreePascalCompile) gedit Plugin Copyright (c) 2011 Florian Harbecke

DOC_DIR=`echo ${GEDIT_CURRENT_DOCUMENT_DIR} | sed "s#$HOME#~#"`

echo "Compiling $GEDIT_CURRENT_DOCUMENT_NAME ($DOC_DIR)"
# Using & so gedit won't freeze if fpc crashes
fpc $GEDIT_CURRENT_DOCUMENT_PATH &
